### ISSUE TITLE
Conditionals in loop

### ISSUE THREAD

**Issue by peet86** [pyrocms/lex#7]
Conditionals in loop doesn't work for me..
Ex: 

$product->cond="yes"

....

{{products}}
   {{if cond=="yes"}}YES!{{endif}} // not work
  {{cond}}        //work
{{/products}}

**Comment by chadwithuhc** [comment]
I submitted a pull request which believe is the same problem as this. See that here: #9

**Comment by dhrrgn** [comment]
This is fixed by d18a825890356855935ea66cbe0957d8982b8606.  Sorry for the delay on this.

**Comment by gravataLonga** [comment]
I still can't do this, any one can help me here?  

HTML:  

``` html
{{ if pets }}
  {{pets}}
   {{nomeMedia.name}}
                            {{if nomeMedia.name!= '' }}
                                {{nomeMedia.name}}
                                <img src="/uploads/{{nomeMedia.name}}" alt="{{ nomePet }} - {{ typePet }}" class="img-rounded img-responsive" />
                            {{endif}}
    {{/pets}}
{{endif}}
```

test php :( 
PHP:  

``` php
$data['pets'] = array(
            array(
                'nomeMedia' => array('name' => 'hello'),
                'nomePet' => 'hello'
            ),
            array(
                'nomeMedia' => array('name' => 'hello1'),
                'nomePet' => 'hello1'
            ),
        );
```

PRINT OUT:    

``` html
<div class="col-sm-6 col-md-4">
                            <!-- 380 x 500 -->
                            hello

                        </div>
<div class="col-sm-6 col-md-4">
                            <!-- 380 x 500 -->
                            hello1

                        </div>
```

So, only print one hello... i can't see where is "conditions" to what happen here.. if i found i will fixed it.
